 name: Pikpak2Onedrive
 on: workflow_dispatch
 jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Rclone
    uses: AnimMouse/setup-rclone@v1
    run: 'rclone lsd --http-url https://beta.rclone.org :http:'
  run: 'rclone lsd :http:'
     env:
      RCLONE_HTTP_URL: https://beta.rclone.org
      
     - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: move Pikpak:/test Onedrive:/
    

    



