name: Pikpak2Onedrive
on: workflow_dispatch
jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: AnimMouse/setup-rclone@v1
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      with:
        args: move Pikpak:/test Onedrive:/
