name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: NiceLabs/rclone-action@master
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          config: ${{ secrets.RCLONE_CONFIG }}
          config-secret-name: RCLONE_CONFIG
      - name: Upload Pre-built images
        run: rclone move Pikpak:/test Onedrive:/
       
