 name: Pikpak2Onedrive
 on: workflow_dispatch
 jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: |
        [rclone-test-remote]
        type = http
        url = https://beta.rclone.org/test/
       disable_base64: true
      
    -  run: 'rclone lsd rclone-test-remote:'

    

    



